# server port setting
server:
  servlet:
    encoding:
      charset: utf-8
  port: 5000

  # 2칸 공백, 탭키 절대 사용 금지!
  # 로그 설정 (개발환경용)
  # 로그 레벨의 개념
  # ERROR > WARN > INFO > DEBUG > TRACE
  logging:
    level:
      root: WARN
      com.tenco.blog: INFO           # 운영 시 중요한 로그만



